// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Quartz.Plugins.RecentHistory.EFCoreSqlite;

#nullable disable

namespace Quartz.Plugins.RecentHistory.EFCoreSqlite.Migrations
{
    [DbContext(typeof(ExecutionHistoryDbContext))]
    partial class ExecutionHistoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Quartz.Plugins.RecentHistory.EFCoreSqlite.ExecutionHistoryDbContext+ExecutionHistoryRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ActualFireTimeUtc")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("actual_fire_time_utc");

                    b.Property<string>("ExceptionMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("exception_message");

                    b.Property<string>("FinishedTimeUtc")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("finished_time_utc");

                    b.Property<string>("FireInstanceId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("fire_instance_id");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("job_name");

                    b.Property<int>("Recovering")
                        .HasColumnType("INTEGER")
                        .HasColumnName("recovering");

                    b.Property<string>("ScheduledFireTimeUtc")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("scheduled_fire_time_utc");

                    b.Property<string>("SchedulerInstanceId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("scheduler_instance_id");

                    b.Property<string>("SchedulerName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("scheduler_name");

                    b.Property<string>("TriggerName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("trigger_name");

                    b.Property<int>("Vetoed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("vetoed");

                    b.HasKey("Id");

                    b.HasIndex("FireInstanceId")
                        .IsUnique();

                    b.HasIndex("SchedulerName", "JobName");

                    b.HasIndex("SchedulerName", "TriggerName");

                    b.ToTable("tb_quartz_ExecutionHistoryStore", (string)null);
                });

            modelBuilder.Entity("Quartz.Plugins.RecentHistory.EFCoreSqlite.ExecutionHistoryDbContext+JobStatsRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("TotalJobsExecuted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_jobs_executed");

                    b.Property<int>("TotalJobsFailed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_jobs_failed");

                    b.HasKey("Id");

                    b.ToTable("tb_quartz_JobStats", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
